### ISSUE TITLE
ADB port problem for hyperV

### ISSUE THREAD

**Issue by flecian** [niels-db/Rush-Royale-Bot#16]
ADB port always changing with hyper V. Can you solve this problem

**Comment by kingchenc** [comment]
This is a bluestacks thing...

but... Google > https://www.reddit.com/r/BlueStacks/comments/qzlhg9/disabling_randomized_adb_port_on_bluestacks_5/

**Comment by Piet-Jacobs** [comment]
Nothing you can do about it...
