### ISSUE TITLE
Can't start bot

### ISSUE THREAD

**Issue by zbiheq** [niels-db/Rush-Royale-Bot#24]
kinda noob at this and don't understand why bot can't start. Get this message in console

File "C:\Rush-Royale-Bot-new-features\Src\bot_core.py", line 24, in __init__
    self.selected_units = os.listdir("units")
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'units'

**Comment by hatehackppl** [comment]
create a new folder named it (units)

**Comment by zbiheq** [comment]
Thanks, now it works
