### ISSUE TITLE
Dryad not merging with dps unit

### ISSUE THREAD

**Issue by Piet-Jacobs** [niels-db/Rush-Royale-Bot#3]
See https://github.com/AxelBjork/Rush-Royale-Bot/issues/84#issuecomment-1650321735

**Comment by Piet-Jacobs** [comment]
After testing I noticed it indeed does not merge if you run Dryad wihout HQ.
Because I had this line with 'and': 
https://github.com/niels-db/Rush-Royale-Bot/blob/6f52fc5ec487b21091729b06468f97b47058178f/Src/bot_core.py#L313C10-L313C10

Should be 'or' instead.

Let me know if that fixes it.

**Comment by Newb420** [comment]
> After testing I noticed it indeed does not merge if you run Dryad wihout HQ. Because I had this line with 'and': https://github.com/niels-db/Rush-Royale-Bot/blob/6f52fc5ec487b21091729b06468f97b47058178f/Src/bot_core.py#L313C10-L313C10
> 
> Should be 'or' instead.
> 
> Let me know if that fixes it.

seems to fixed it awesome work!

**Comment by ToxicGigante** [comment]
hello how do I add this into the scrip I no -1 info on how to do any of this stuff with script I got lucky with being able to get the bot to work on the game

**Comment by ToxicGigante** [comment]
> hello how do I add this into the scrip I no -1 info on how to do any of this stuff with script I got lucky with being able to get the bot to work on the game

@Piet-Jacobs @Newb420
