### ISSUE TITLE
Unit Identification

### ISSUE THREAD

**Issue by EtAnimis** [niels-db/Rush-Royale-Bot#6]
The bot very commonly mistakes summoner for dryad and will continue to try and merge a summoner with any other card.

**Comment by Piet-Jacobs** [comment]
Not much we can do about that, I suggest you stop using summoner and dryad in the same deck for now

**Comment by Newb420** [comment]
> The bot very commonly mistakes summoner for dryad and will continue to try and merge a summoner with any other card.

while you're playing go into the OCR_input folder and grab a fresh icon and replace it with the one in all units folder works for me done this to many units now. make sure its 90x90 tho if u crop it

**Comment by Newb420** [comment]
currently just got summoner and using with dryad i cropped new pictures for dryad now the bot can identify them just fine here they are just incase i did something to summoner. 
![summoner](https://github.com/niels-db/Rush-Royale-Bot/assets/77933521/02695be8-ac3f-4791-8910-f5f0f9870362)
![dryad](https://github.com/niels-db/Rush-Royale-Bot/assets/77933521/4935c572-9e14-4762-acbf-fe511709b415)

**Comment by Newb420** [comment]
> The bot very commonly mistakes summoner for dryad and will continue to try and merge a summoner with any other card.



> Not much we can do about that, I suggest you stop using summoner and dryad in the same deck for now

currently just got summoner and using with dryad i cropped new pictures for dryad now the bot can identify them just fine here they are just incase i did something to summoner. 
![summoner](https://github.com/niels-db/Rush-Royale-Bot/assets/77933521/02695be8-ac3f-4791-8910-f5f0f9870362)
![dryad](https://github.com/niels-db/Rush-Royale-Bot/assets/77933521/4935c572-9e14-4762-acbf-fe511709b415)

**Comment by niels-db** [comment]
Thank you @Newb420 ! I added these images in release 1.19.
It is very common the bot makes unit detection mistakes. There is no perfect solution for this, certain images will work better for certain floors than others. You can always add your own images as @Newb420 suggested.
