### ISSUE TITLE
Guild stuff

### ISSUE THREAD

**Issue by kingchenc** [niels-db/Rush-Royale-Bot#9]
maybe we have this in the future...

guild unit reqeust
guild collect gifs
guild spend to other player units

**Comment by niels-db** [comment]
Hi kingchenc, I've released some clan related things:

- [x] Play clan tournament/sandals
- [x] Collect gifts from clan chat
- [x] Request units in the clan chat
- [ ] Guild give units to other players (not planning to implement this atm)

**Comment by kingchenc** [comment]
Hey and thanks :)

Nice so see that @niels-db , testing soon this new stuff <3
